version: '3.8' # Spécifiez la version pour éviter des comportements inattendus
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    networks:
      - keycloak-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

  authentification-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: authentification-service
    networks:
      - keycloak-network
    env_file:
      - .env
    ports:
      - "8083:8083"
    dns:
      - 8.8.8.8
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:

networks:
  keycloak-network:
    name: keycloak-network
    external: true