version: '3.8'
services:
  kafka1:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka1
    user: root
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:8092,CONTROLLER://0.0.0.0:8093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:9092,EXTERNAL://localhost:8092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:8093,2@kafka2:8095,3@kafka3:8097
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_LOG_RETENTION_HOURS: 168
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_LOG_DIRS: /tmp/kraft
      KAFKA_CONFLUENT_KRAFT_MODE: 'true'
    ports:
      - "8092:8092"
      - "8093:8093"
    volumes:
      - kafka1-data:/tmp/kraft
    networks:
      kafka-network:
        aliases:
          - kafka1
  kafka2:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka2
    user: root
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9094,EXTERNAL://0.0.0.0:8094,CONTROLLER://0.0.0.0:8095
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka2:9094,EXTERNAL://localhost:8094
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:8093,2@kafka2:8095,3@kafka3:8097
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_LOG_RETENTION_HOURS: 168
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_LOG_DIRS: /tmp/kraft
      KAFKA_CONFLUENT_KRAFT_MODE: 'true'
    ports:
      - "8094:8094"
      - "8095:8095"
    volumes:
      - kafka2-data:/tmp/kraft
    networks:
      kafka-network:
        aliases:
          - kafka2
  kafka3:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka3
    user: root
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9096,EXTERNAL://0.0.0.0:8096,CONTROLLER://0.0.0.0:8097
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka3:9096,EXTERNAL://localhost:8096
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:8093,2@kafka2:8095,3@kafka3:8097
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_LOG_RETENTION_HOURS: 168
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_LOG_DIRS: /tmp/kraft
      KAFKA_CONFLUENT_KRAFT_MODE: 'true'
    ports:
      - "8096:8096"
      - "8097:8097"
    volumes:
      - kafka3-data:/tmp/kraft
    networks:
      kafka-network:
        aliases:
          - kafka3
networks:
  kafka-network:
    driver: bridge
volumes:
  kafka1-data:
  kafka2-data:
  kafka3-data: