services:
  mysql_gestion_projets:
    image: mysql:8.0
    container_name: mysql_gestion_projets
    networks:
      - keycloak-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3308:3306"
    volumes:
      - gestion_projet_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

  github-integration-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: github-integration-service
    networks:
      - keycloak-network
    env_file:
      - .env
    ports:
      - "8087:8087"
    dns:
      - 8.8.8.8
    depends_on:
      mysql_gestion_projets:
        condition: service_healthy

volumes:
  gestion_projet_data:

networks:
  keycloak-network:
    name: keycloak-network
    external: true