global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nextjs_frontend'
    metrics_path: '/api/metrics'  
    static_configs:
      - targets: ['host.docker.internal:3000'] 
        labels:
          group: 'frontend'
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] 
  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091'] 
        labels:
          group: 'ci_cd'


          