name: CI/CD with DevSecOps and Docker for Next.js

on:
  push:
    branches: [main]
    paths:
      - 'front-end_service/**'
  pull_request:
    branches: [main]
    paths:
      - 'front-end_service/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front-end_service  # Set working directory
    steps:
      # Step 1: Clone the code source
      - name: Checkout Source Code
        uses: actions/checkout@v4

      # Step 2: Configure Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm ci

      # Step 4: Check vulnerabilities
      - name: Check Dependencies for Vulnerabilities
        run: npm audit --audit-level=high
        continue-on-error: true

      # Step 5: Static analysis with ESLint
      - name: Run ESLint Security Scan
        run: npm run lint
        continue-on-error: true

      # Step 6: Build Next.js app
      - name: Build Next.js App
        run: npm run build
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}

      # Step 7: Run tests
      - name: Run Tests
        run: npm run test

      # Step 8: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 9: Build and push Docker image
      - name: Build and Push Docker Image
        if: github.event_name == 'push'
        uses: docker/build-push-action@v5
        with:
          context: ./front-end_service  # Adjust context to front-end_service
          file: ./front-end_service/Dockerfile  # Adjust path to Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:latest,ghcr.io/${{ github.repository }}:${{ github.sha }}
          platforms: linux/amd64
